# Generated by Django 3.2.9 on 2021-11-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='image',
            field=models.ImageField(default='북촌.jpeg', upload_to=''),
        ),
    ]
