# Generated by Django 3.2.9 on 2021-11-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_auto_20211113_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foot_traffic',
            old_name='name',
            new_name='place',
        ),
    ]
